# Generated by Django 5.2.4 on 2025-07-27 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiowork',
            options={},
        ),
        migrations.AlterField(
            model_name='audiowork',
            name='audio_file',
            field=models.FileField(upload_to='audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])], verbose_name='فایل صوتی'),
        ),
    ]
