# Generated by Django 5.2.5 on 2026-08-29 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_alter_audiowork_options_alter_audiowork_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiowork',
            name='audio_file',
            field=models.FileField(upload_to='audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a', 'mp4'])], verbose_name='فایل صوتی'),
        ),
    ]
