# Generated by Django 5.2.4 on 2025-07-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='فایل ویدیویی')),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='slider_images/', verbose_name='تصویر اسلایدر (اختیاری)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='دسته\u200cبندی')),
            ],
        ),
    ]
