# Generated by Django 5.2.4 on 2025-07-27 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videowork',
            name='slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='تصویر برای اسلایدر (اختیاری)'),
        ),
        migrations.AlterField(
            model_name='videowork',
            name='video_file',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mov', 'avi', 'webm'])], verbose_name='فایل ویدیویی'),
        ),
    ]
