# Generated by Django 5.2.4 on 2025-07-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اسلاید')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='تصویر اسلایدر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک (اختیاری)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
            },
        ),
    ]
