# Generated by Django 5.2.5 on 2026-06-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='درباره دکتر محمد رضا کمن', max_length=200, verbose_name='عنوان صفحه')),
                ('content', models.TextField(verbose_name='محتوای صفحه درباره')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'صفحه درباره',
                'verbose_name_plural': 'صفحه درباره',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='تماس با ما', max_length=200, verbose_name='عنوان صفحه')),
                ('content', models.TextField(verbose_name='محتوای صفحه تماس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'صفحه تماس',
                'verbose_name_plural': 'صفحه تماس',
            },
        ),
    ]
