# Generated by Django 5.2.4 on 2025-07-27 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textwork',
            options={},
        ),
        migrations.AlterField(
            model_name='textwork',
            name='file',
            field=models.FileField(upload_to='texts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'epub'])], verbose_name='فایل'),
        ),
    ]
